### ISSUE TITLE
key_exchange_noalloc

### ISSUE THREAD

**Issue by cfcs** [mirage/hacl#11]
Would it make sense to expose a non-allocating version of `key_exchange` where the user provides the result buffer?

ping @emillon @dinosaure @NathanReb @pascutto

**Comment by hannesm** [comment]
but why? I mean what is the actual use case? and what should `key_exchange` (atm no result return) do if the provided buffer is too small/too big?

**Comment by emillon** [comment]
I'm not too sure about this one. There's the problem of error semantics for the output buffer, but also I don't think key exchange is usually performance sensitive, so a fresh buffer usually is enough.

**Comment by cfcs** [comment]
Fair enough, when discussing with @hannesm some weeks ago he pointed out that it increased the risk for accidentally reusing the buffer, which I think is an excellent argument against this.
