### ISSUE TITLE
Leave the GC lock in the C stub

### ISSUE THREAD

**Issue by dinosaure** [mirage/hacl#13]
Need a benchmark, however.

**Comment by emillon** [comment]
Hi!

Does this mean `@noalloc`?
I don't think that we require this amount of performance tuning. This is not super performance critical, and it's probably doing enough things on the C side that it wouldn't be visible.

**Comment by dinosaure** [comment]
No it's about to leave the GC global lock when we compute the bigarray behind. Currently, any call to the `blit` function on 2 bigarrays for example [leave the GC lock](https://github.com/ocaml/ocaml/blob/trunk/runtime/bigarray.c#L1087) then `len > 4096`. `digestif` [leave the lock too](https://github.com/mirage/digestif/pull/70) and let the user to digest in a (real) parallel process inputs. In a `Lwt`/`Async` context, it can be interesting to allow that.

**Comment by emillon** [comment]
OK, thanks for the pointers. I don't think we need to go into that territory.
Performance is already good enough for our use cases, so let's not spend more time on optimizing this.

Thanks!

**Comment by hannesm** [comment]
> Performance is already good enough for our use cases

I discovered there is a bench subfolder in the tree, are there any comparisons to a baseline (e.g. the original C-hacl, ...)?, or how did you come to the conclusion that it's 'already good enough'?

**Comment by emillon** [comment]
That was used to detect regressions when doing the initial bindings - cstruct vs string, moving the FFI boundaries, porting BoringSSL C code to OCaml, etc.

As for the performance, there's one key exchange operation per connection, so even if it was 10ms long it wouldn't be great but that would be enough for a first release.
