### ISSUE TITLE
Release v0.2.0

### ISSUE THREAD

**Issue by dinosaure** [mirage/hacl#39]
Mostly due to #35 and #36, you probably should cut a release. Are you ok with that @hannesm?

**Comment by hannesm** [comment]
hello,

> you probably should cut a release

who's this "you"?

> Are you ok with that @hannesm?

I'd like to investigate / implement usage of Ed25519 keys in e.g. OpenSSH or X.509 first to figure out whether the hacl API is missing something for this purpose (I suspect it'll need to expose the raw Cstruct.t data of the private key to encode and decode it). I'll likely do this until end of this week, if you need a release as fast as possible to unblock other development, please go ahead and cut a release.

**Comment by dinosaure** [comment]
> who's this "you"?

You or me (I have time to do that) :)

> I'd like to investigate / implement usage of Ed25519 keys in e.g. OpenSSH or X.509 first to figure out whether the hacl API is missing something for this purpose (I suspect it'll need to expose the raw Cstruct.t data of the private key to encode and decode it). I'll likely do this until end of this week, if you need a release as fast as possible to unblock other development, please go ahead and cut a release.

Ok, so tell me when it's done :+1:

**Comment by hannesm** [comment]
done in https://github.com/ocaml/opam-repository/pull/16895
