### ISSUE TITLE
unify repository and opam package name

### ISSUE THREAD

**Issue by hannesm** [mirage/hacl#4]
Hi,

the repository is named `ocaml-hacl-ecc`. The opam package is named `hacl_x25519`. Is this intentional? I suggest to unify these two, and propose either `hacl-ecc` (since in the future there may be other curves implemented as well) or `hacl-x25519`. I don't see a reason to keep the `ocaml-` prefix as part of the repository name. Thanks.

**Comment by emillon** [comment]
I was thinking of having keeping opam package per primitive. But in the end this will bind more than just ECC, so there will be `hacl-poly1305`, etc. What do you think of just `mirage/hacl` with `hacl-XXX` opam packages?

**Comment by hannesm** [comment]
@emillon that sounds fine to me as well :+1:

**Comment by emillon** [comment]
@hannesm can you rename this repo "hacl"? (I lack admin rights to do that). I'll take care of changing opam metadata etc. Thanks!

**Comment by hannesm** [comment]
@emillon done, his is now `mirage/hacl`.

**Comment by emillon** [comment]
Thanks @hannesm !
